### PR TITLE
fixed for 0.4/Colors.jl

### PR DESCRIPTION
**Pull request by cormullion**
although the output SVG is a bit different (colors are in a slightly
different order from before), this particular file is only a
quick-reference/pretty handout, so the changes aren’t significant… :)

### CODE REVIEW

**Comment by cormullion** [comment]
failure is due to #15 I think

**Comment by timholy** [comment]
Out of curiosity, what error did this fix?

**Comment by cormullion** [comment]
@timholy Well for one thing I left `#!/Applications/Julia-0.3.9.app...` at the top of the file. (Bad habit I have... :)) Also I changed the color comparison code (`hslx = convert(LUV, RGB(rx, gx, bx))` 😱). But the failure of the tests is due to the colormap issues in #15.

**Comment by timholy** [comment]
I guess what I meant is: what is the motivation for this PR? Was it a deprecation warning, an error message, an incorrect answer, or something else?

**Comment by cormullion** [comment]
Your revision of Aug 22 changed Color to Colors, but then the file failed with the error:

    ERROR: LoadError: UndefVarError: LUV not defined
     in compare_colors 

(after changing the shebang line). I thought I'd better fix it (and improve it while I was there).

**Comment by timholy** [comment]
OK, thanks!

**Pull request merged**
