### PR TITLE
Updated PackageEvaluator shields

### PR DESCRIPTION
**Pull request by Nosferican**
These now match the tested versions in CI (Julia 0.6 and nightly).

### CODE REVIEW

**Comment by cormullion** [comment]
I incorporated these badge/shield changes into the revised README.md which I (somewhat over-enthusiastically 😀) added today.

**Comment by timholy** [comment]
These are broken now.

**Comment by cormullion** [comment]
Yes, do you think PkgEvaluator will return with badges as before?

**Comment by timholy** [comment]
I haven't followed it at all, sorry.

**Comment by ararslan** [comment]
Unlikely for the foreseeable future.

**Comment by ararslan** [comment]
Superseded by #345

**Pull request closed without merging**
