### PR TITLE
Update TagBot.yml

### PR DESCRIPTION
**Pull request by kimikage**
cf. https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249

// Sorry for the messy branch name as I thought I had created the branch in my fork.

### CODE REVIEW

**Comment by kimikage** [comment]
BTW, I think the v0.12.4 documentation will be permanently missing if we don't run the generation manually before the next tag release. There should be no documentation changes between v0.12.3 and v0.12.4, so we might just need to manually copy the documentation for v0.12.3.

**Comment by johnnychen94** [comment]
Probably it's better for @timholy to do [massive update](https://github.com/bcbi/MassInstallAction.jl) via direct commit to all related repos.

**Comment by timholy** [comment]
That's my intention. I'm still digging out from some deadlines last week and wanting to push one or two more things over the finish line for the 1.6 feature freeze, but I'll do this fairly soon.

**Comment by kimikage** [comment]
I saw that @timholy executed the MassInstallAction for packages under his personal repositories. :smile:
I am currently thinking of merging this single PR in order to release PR #451 as v0.12.5.

BTW, after the updating of TagBot, "Fixing broken release deployments" seems to be available for v0.12.4 documentation.
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions

**Comment by kimikage** [comment]
I will update only Colors.jl manually.

**Comment by kimikage** [comment]
Also, I generated the docs for v0.12.4 with the TagBot action: http://juliagraphics.github.io/Colors.jl/v0.12.4/
So, the permission setting (`ssh: ${{ secrets.TAGBOT }}`) works fine!

**Pull request merged**
