### PR TITLE
Add Color string-literal macro: Color"red"

### PR DESCRIPTION
**Pull request by timholy**
Implements the approach discussed in https://github.com/JuliaGraphics/Colors.jl/pull/1#issuecomment-133358533

### CODE REVIEW

**Comment by timholy** [comment]
I should have mentioned that it also adds a deprecation warning for `color("red")`.

CCing @dcjones

**Comment by kmsquire** [comment]
I think I would also prefer `color"red"` to `Color"red"`. The latter somehow suggests a closer relationship to the abstract type `Color` than actually exists.

**Comment by Keno** [comment]
+1 to `color"red`"

**Comment by timholy** [comment]
Closing in favor of #5. Let's continue the discussion there.

**Pull request closed without merging**
