### PR TITLE
Update docs to highlight wavelength to RGB conversion

### PR DESCRIPTION
**Pull request by ianshmean**
As discussed in #334 

Based on https://gist.github.com/friendly/67a7df339aa999e2bcfcfec88311abfc
Which is a conversion of code by Dan Bruton http://www.physics.sfasu.edu/astro/color/spectra.html
And discussed: https://stackoverflow.com/questions/1472514/convert-light-frequency-to-rgb

### CODE REVIEW

**Comment by ianshmean** [comment]
I also corrected the version in `Project.toml` and deleted `REQUIRE`

**Comment by ianshmean** [comment]
Closing as it turns out a more accurate method is already provided via
```julia
using Colors
RGB.(colormatch.(320:800))
```

**Comment by cormullion** [comment]
How about turning this into a documentation PR? It’s clearly needed. 😀

**Comment by ianshmean** [comment]
@cormullion Good idea. I've added a short example and figure

**Pull request merged**
